### ISSUE TITLE
We should remove gpg signing stuff from PRs

### ISSUE THREAD

**Issue by justinabrahms** [open-feature/java-sdk#37] opened 2022-07-23 21:10 UTC
When someone forks and makes a PR, the build fails on the GPG portions. We should exclude that from PR building

**Comment by thomaspoignant** [comment] 2022-07-23 21:24
This is a duplicate of this issue I have created already https://github.com/open-feature/java-sdk/issues/36

**Comment by justinabrahms** [comment] 2022-07-23 21:26
Thanks. The UI wasn't loading for me so I did it from the CLI and didn't check for existing issues

**Closed** 2022-07-23 21:25 UTC
