### ISSUE TITLE
Maven Central and javadoc badges have a status of unknown

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/java-sdk#129] opened 2022-10-06 21:04 UTC
![image](https://user-images.githubusercontent.com/682996/194418000-c3f32e9d-5204-43ae-8859-af3217e0fd5f.png)

**Comment by justinabrahms** [comment] 2022-10-13 04:31
This is because we've moved the package from `javasdk` to `sdk`. When we make a release, it should be fixed.

**Comment by toddbaert** [comment] 2022-10-13 11:52
Confirmed the above, after 0.3.0, this looks good, closing.

**Closed by toddbaert** 2022-10-13 11:52 UTC
